/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TouristServer
 * OpenAPI spec version: 1.0
 */

export interface FilterDto {
  /** @nullable */
  categoryIds?: string[] | null;
  /** @nullable */
  districtIds?: string[] | null;
  /** @nullable */
  constMin?: number | null;
  /** @nullable */
  constMax?: number | null;
}
