/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TouristServer
 * OpenAPI spec version: 1.0
 */

export type GetV1PlacesPhotosOfPlacePlaceIdParams = {
page?: number;
pageSize?: number;
};
