/* tslint:disable */
/* eslint-disable */
/**
 * TouristServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceDto
 */
export interface PlaceDto {
    /**
     * 
     * @type {string}
     * @memberof PlaceDto
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlaceDto
     */
    photosUrl?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceDto
     */
    categoryName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceDto
     */
    districtName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlaceDto
     */
    cost?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaceDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaceDto
     */
    longitude?: number;
}

/**
 * Check if a given object implements the PlaceDto interface.
 */
export function instanceOfPlaceDto(value: object): value is PlaceDto {
    return true;
}

export function PlaceDtoFromJSON(json: any): PlaceDto {
    return PlaceDtoFromJSONTyped(json, false);
}

export function PlaceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'photosUrl': json['photosUrl'] == null ? undefined : json['photosUrl'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function PlaceDtoToJSON(value?: PlaceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'photosUrl': value['photosUrl'],
        'categoryName': value['categoryName'],
        'description': value['description'],
        'name': value['name'],
        'districtName': value['districtName'],
        'cost': value['cost'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

