/* tslint:disable */
/* eslint-disable */
/**
 * TouristServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoutePlaceDto
 */
export interface RoutePlaceDto {
    /**
     * 
     * @type {number}
     * @memberof RoutePlaceDto
     */
    placePosition?: number;
    /**
     * 
     * @type {string}
     * @memberof RoutePlaceDto
     */
    placeId?: string;
    /**
     * 
     * @type {string}
     * @memberof RoutePlaceDto
     */
    placeName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RoutePlaceDto
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoutePlaceDto
     */
    longitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoutePlaceDto
     */
    cost?: number;
}

/**
 * Check if a given object implements the RoutePlaceDto interface.
 */
export function instanceOfRoutePlaceDto(value: object): value is RoutePlaceDto {
    return true;
}

export function RoutePlaceDtoFromJSON(json: any): RoutePlaceDto {
    return RoutePlaceDtoFromJSONTyped(json, false);
}

export function RoutePlaceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutePlaceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'placePosition': json['placePosition'] == null ? undefined : json['placePosition'],
        'placeId': json['placeId'] == null ? undefined : json['placeId'],
        'placeName': json['placeName'] == null ? undefined : json['placeName'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'cost': json['cost'] == null ? undefined : json['cost'],
    };
}

export function RoutePlaceDtoToJSON(value?: RoutePlaceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'placePosition': value['placePosition'],
        'placeId': value['placeId'],
        'placeName': value['placeName'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'cost': value['cost'],
    };
}

