/* tslint:disable */
/* eslint-disable */
/**
 * TouristServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoute } from './UserRoute';
import {
    UserRouteFromJSON,
    UserRouteFromJSONTyped,
    UserRouteToJSON,
} from './UserRoute';
import type { Place } from './Place';
import {
    PlaceFromJSON,
    PlaceFromJSONTyped,
    PlaceToJSON,
} from './Place';

/**
 * 
 * @export
 * @interface RoutePlace
 */
export interface RoutePlace {
    /**
     * 
     * @type {string}
     * @memberof RoutePlace
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof RoutePlace
     */
    placePosition?: number;
    /**
     * 
     * @type {string}
     * @memberof RoutePlace
     */
    userRouteId?: string;
    /**
     * 
     * @type {UserRoute}
     * @memberof RoutePlace
     */
    userRoute?: UserRoute;
    /**
     * 
     * @type {string}
     * @memberof RoutePlace
     */
    placeId?: string;
    /**
     * 
     * @type {Place}
     * @memberof RoutePlace
     */
    place?: Place;
}

/**
 * Check if a given object implements the RoutePlace interface.
 */
export function instanceOfRoutePlace(value: object): value is RoutePlace {
    return true;
}

export function RoutePlaceFromJSON(json: any): RoutePlace {
    return RoutePlaceFromJSONTyped(json, false);
}

export function RoutePlaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutePlace {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'placePosition': json['placePosition'] == null ? undefined : json['placePosition'],
        'userRouteId': json['userRouteId'] == null ? undefined : json['userRouteId'],
        'userRoute': json['userRoute'] == null ? undefined : UserRouteFromJSON(json['userRoute']),
        'placeId': json['placeId'] == null ? undefined : json['placeId'],
        'place': json['place'] == null ? undefined : PlaceFromJSON(json['place']),
    };
}

export function RoutePlaceToJSON(value?: RoutePlace | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'placePosition': value['placePosition'],
        'userRouteId': value['userRouteId'],
        'userRoute': UserRouteToJSON(value['userRoute']),
        'placeId': value['placeId'],
        'place': PlaceToJSON(value['place']),
    };
}

