/* tslint:disable */
/* eslint-disable */
/**
 * TouristServer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoute } from './UserRoute';
import {
    UserRouteFromJSON,
    UserRouteFromJSONTyped,
    UserRouteToJSON,
} from './UserRoute';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    hashPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    refreshToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    role?: string | null;
    /**
     * 
     * @type {Array<UserRoute>}
     * @memberof User
     */
    routes?: Array<UserRoute> | null;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'hashPassword': json['hashPassword'] == null ? undefined : json['hashPassword'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'role': json['role'] == null ? undefined : json['role'],
        'routes': json['routes'] == null ? undefined : ((json['routes'] as Array<any>).map(UserRouteFromJSON)),
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'hashPassword': value['hashPassword'],
        'refreshToken': value['refreshToken'],
        'role': value['role'],
        'routes': value['routes'] == null ? undefined : ((value['routes'] as Array<any>).map(UserRouteToJSON)),
    };
}

